### ISSUE TITLE
TA Feedback (milestone 2): Code/procedures

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group29#72]
- `explore_script4.py` is extremely hard to read. I suggest splitting this into a few more functions, and also adding a main function as shown in class.
- The train/test split should be done within the data processing script. Make sure you set a seed when doing this as well. Then, your EDA should be done using only the training data!
  - This would also fix the issue you have in `eda2.py` where results are not reproducible since you don't set a seed. 
- Some of the script names could be changed so they are more informative

**Comment by rachelywong** [comment]
@wiwang  create 3 functions and a main function in script 4, after we edit script 4
@wiwang move train/test split
@jraza19 seed
@rachelywong  change script 5 name

**Comment by rachelywong** [comment]
Hi @jbourak,

We were just discussing in lab today with Analise, the feedback about the train/test split being done within the data processing script. After reviewing our scripts and the downstream changes that would need to be done to make these changes, we decided that the best option for our project to address the train/test split feedback would be to:

1. Apply Pandas Profiling on the raw data set as we originally had done. The reasoning for this is so that we can do an EDA to understand what our raw data set looks like, particularly types of features and null/missing values.
2. Split the processed data set before we do EDA into training and testing data, and apply our EDA analysis on the training data created.
3. From our EDA results, we can see that the race feature is not informative to answering our project question. Therefore, we will remove race from the processed data set, and in our model development and further analysis we will split this new processed data set (with race removed) into training and testing, and continue on with these new training and testing sets.
4. By doing so, our EDA will be done only using the training data which limits bias on us knowing the test data.
5. Also we can add a random_state to ensure our seed is set during the splits. 

Please let us know if these steps address the feedback you have given us, these steps will also ensure we do not have to make too many changes to our downstream scripts and Makefile so we can have more time to focus on other parts of Milestone 4.

**Comment by rachelywong** [comment]
Completed with reasoning ^
